import { type Review, type ReviewStats, type PostServiceFollowUp } from "@/lib/types";

/* ── Mock Reviews (20 across different pros) ──────────────────── */

export const mockReviews: Review[] = [
  // Alex Martinez (pro_1) — Home Inspector — 6 reviews
  {
    id: "review_1",
    proId: "pro_1",
    consumerId: "user_morgan",
    consumerName: "Morgan Davis",
    journeyId: "journey_3",
    rating: 5,
    title: "Best inspector we could have asked for",
    body: "Alex was incredibly thorough with our Evanston Victorian. He spent over 3 hours going through every detail — roof, foundation, electrical, plumbing — and explained everything in plain English. His report was crystal clear with photos and annotations. Found a small issue with the attic ventilation that we were able to negotiate into the repair credits. Couldn't recommend more highly.",
    serviceCategory: "Home Inspector",
    verifiedClient: true,
    proResponse: {
      body: "Thank you so much, Morgan! It was a pleasure inspecting your beautiful Victorian. Glad we caught that attic issue early — enjoy your new home! 🏠",
      respondedAt: "2026-02-22T10:00:00Z",
    },
    helpful: 14,
    reported: false,
    createdAt: "2026-02-21T09:00:00Z",
  },
  {
    id: "review_2",
    proId: "pro_1",
    consumerId: "user_jamie",
    consumerName: "Jamie Rodriguez",
    journeyId: "journey_1",
    rating: 5,
    title: "Thorough, professional, and fast",
    body: "Alex inspected our Oak Park bungalow built in 1928. Given the age of the home, I was nervous, but Alex put us at ease immediately. He found some knob-and-tube wiring we didn't know about and gave us honest advice on next steps. Report delivered same day. This is the kind of professional you want in your corner.",
    serviceCategory: "Home Inspector",
    verifiedClient: true,
    helpful: 8,
    reported: false,
    createdAt: "2026-02-16T14:30:00Z",
  },
  {
    id: "review_3",
    proId: "pro_1",
    consumerId: "user_tanya",
    consumerName: "Tanya M.",
    rating: 5,
    body: "Very detailed inspection. Alex took the time to walk us through every finding on-site. His report was easy to read and included thermal imaging photos. Would hire again in a heartbeat.",
    serviceCategory: "Home Inspector",
    verifiedClient: false,
    proResponse: {
      body: "Thanks Tanya! Glad the thermal imaging was helpful — it really does catch things the eye misses. Wishing you all the best with the new place!",
      respondedAt: "2026-02-10T08:00:00Z",
    },
    helpful: 6,
    reported: false,
    createdAt: "2026-02-08T16:00:00Z",
  },
  {
    id: "review_4",
    proId: "pro_1",
    consumerId: "user_kevin",
    consumerName: "Kevin P.",
    rating: 4,
    body: "Good inspection overall. Alex was professional and thorough. Only minor feedback — the report took about 36 hours instead of the promised 24, but the quality was excellent when it arrived. Would still recommend.",
    serviceCategory: "Home Inspector",
    verifiedClient: false,
    helpful: 3,
    reported: false,
    createdAt: "2026-01-28T11:00:00Z",
  },
  {
    id: "review_5",
    proId: "pro_1",
    consumerId: "user_amy",
    consumerName: "Amy L.",
    rating: 5,
    title: "Saved us from a huge mistake",
    body: "Alex found serious foundation issues that the seller hadn't disclosed. We were able to walk away from a bad deal thanks to his expertise. Worth every penny. His radon testing was also incredibly helpful.",
    serviceCategory: "Home Inspector",
    verifiedClient: false,
    helpful: 21,
    reported: false,
    createdAt: "2026-01-15T09:30:00Z",
  },
  {
    id: "review_6",
    proId: "pro_1",
    consumerId: "user_raj",
    consumerName: "Raj K.",
    rating: 3,
    body: "Alex was professional but scheduling was a bit tricky — had to reschedule twice due to conflicts. The actual inspection was solid though, and the report was comprehensive. Just wish the availability was better.",
    serviceCategory: "Home Inspector",
    verifiedClient: false,
    proResponse: {
      body: "Raj, I sincerely apologize for the scheduling difficulties. January was our busiest month and I should have communicated better. I've since added more availability. Thank you for the honest feedback.",
      respondedAt: "2026-01-12T15:00:00Z",
    },
    helpful: 2,
    reported: false,
    createdAt: "2026-01-10T17:00:00Z",
  },

  // Jordan Lee (pro_2) — Mortgage Lender — 4 reviews
  {
    id: "review_7",
    proId: "pro_2",
    consumerId: "user_morgan",
    consumerName: "Morgan Davis",
    journeyId: "journey_3",
    rating: 5,
    title: "Made the mortgage process painless",
    body: "Jordan got us pre-approved in literally one day. He walked us through every option — FHA, conventional, fixed vs ARM — without any pressure. Communication was outstanding throughout. He even called us on a Saturday when we had a question about our rate lock.",
    serviceCategory: "Mortgage Lender",
    verifiedClient: false,
    proResponse: {
      body: "Morgan, it was great working with you! First-time buyers deserve a stress-free experience and I'm glad we could deliver that. Congrats on the new home!",
      respondedAt: "2026-02-23T09:00:00Z",
    },
    helpful: 11,
    reported: false,
    createdAt: "2026-02-22T14:00:00Z",
  },
  {
    id: "review_8",
    proId: "pro_2",
    consumerId: "user_sam",
    consumerName: "Sam Patel",
    rating: 5,
    body: "Jordan is the gold standard for mortgage lenders. Responsive, transparent, competitive rates. He explained the entire process clearly and was always available when we had questions. Closed on time with zero surprises.",
    serviceCategory: "Mortgage Lender",
    verifiedClient: false,
    helpful: 7,
    reported: false,
    createdAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "review_9",
    proId: "pro_2",
    consumerId: "user_elena",
    consumerName: "Elena R.",
    rating: 4,
    title: "Great service, slightly higher rates",
    body: "Jordan was fantastic to work with — super responsive and knowledgeable. The only reason for 4 stars instead of 5 is that we found slightly better rates elsewhere, though Jordan's service was vastly superior. If you value communication and trust, go with Jordan.",
    serviceCategory: "Mortgage Lender",
    verifiedClient: false,
    helpful: 5,
    reported: false,
    createdAt: "2026-01-22T08:00:00Z",
  },
  {
    id: "review_10",
    proId: "pro_2",
    consumerId: "user_michael",
    consumerName: "Michael T.",
    rating: 5,
    body: "Second time using Jordan for a mortgage. Just as excellent as the first time. Pre-approval letter came same day, and he kept us updated every step of the way through closing.",
    serviceCategory: "Mortgage Lender",
    verifiedClient: false,
    helpful: 4,
    reported: false,
    createdAt: "2026-01-05T16:00:00Z",
  },

  // Marcus Williams (pro_4) — Attorney — 3 reviews
  {
    id: "review_11",
    proId: "pro_4",
    consumerId: "user_morgan",
    consumerName: "Morgan Davis",
    journeyId: "journey_3",
    rating: 5,
    title: "Sharp, thorough, and worth every cent",
    body: "Marcus reviewed our purchase contract and caught two clauses that could have cost us thousands. He explained everything in clear language and was available for questions throughout the entire process. His team handled closing seamlessly. If you're buying a home in Illinois, Marcus is who you want.",
    serviceCategory: "Attorney",
    verifiedClient: false,
    proResponse: {
      body: "Thank you Morgan! Those contract details matter more than most people realize. It was a pleasure ensuring everything went smoothly for your closing. Enjoy the Evanston Victorian!",
      respondedAt: "2026-02-24T11:00:00Z",
    },
    helpful: 9,
    reported: false,
    createdAt: "2026-02-23T10:00:00Z",
  },
  {
    id: "review_12",
    proId: "pro_4",
    consumerId: "user_lisa_client",
    consumerName: "David W.",
    rating: 5,
    body: "Marcus and his team were incredibly professional. Contract review was completed in 48 hours as promised. He found issues with the seller's disclosure that we wouldn't have caught. Highly recommend for any real estate transaction.",
    serviceCategory: "Attorney",
    verifiedClient: false,
    helpful: 6,
    reported: false,
    createdAt: "2026-02-01T13:00:00Z",
  },
  {
    id: "review_13",
    proId: "pro_4",
    consumerId: "user_casey",
    consumerName: "Casey W.",
    rating: 4,
    body: "Very competent attorney. Marcus handled our closing professionally. Only minor gripe — his office was sometimes slow to return calls, but when we did connect, the advice was always spot-on.",
    serviceCategory: "Attorney",
    verifiedClient: false,
    helpful: 2,
    reported: false,
    createdAt: "2026-01-18T15:00:00Z",
  },

  // Sarah Chen (pro_3) — Insurance Agent — 2 reviews
  {
    id: "review_14",
    proId: "pro_3",
    consumerId: "user_morgan",
    consumerName: "Morgan Davis",
    journeyId: "journey_3",
    rating: 4,
    title: "Quick quotes, solid coverage",
    body: "Sarah got us three different quotes within an hour. She explained the difference between HO-3 and HO-5 policies clearly and helped us pick the right coverage level. Saved us about $400/year compared to what we were initially quoted elsewhere.",
    serviceCategory: "Insurance Agent",
    verifiedClient: false,
    helpful: 4,
    reported: false,
    createdAt: "2026-02-15T11:00:00Z",
  },
  {
    id: "review_15",
    proId: "pro_3",
    consumerId: "user_jessica",
    consumerName: "Jessica H.",
    rating: 5,
    body: "Sarah is amazing. She took the time to explain every line of our policy and made sure we had adequate coverage for our condo. Her follow-up after the policy was in place was also fantastic. Truly cares about her clients.",
    serviceCategory: "Insurance Agent",
    verifiedClient: false,
    proResponse: {
      body: "Thank you Jessica! Making insurance understandable is what I'm most passionate about. Don't hesitate to reach out if you ever have questions about your coverage!",
      respondedAt: "2026-01-30T09:00:00Z",
    },
    helpful: 3,
    reported: false,
    createdAt: "2026-01-28T10:00:00Z",
  },

  // Lisa Hartwell (pro_9) — Realtor — 3 reviews
  {
    id: "review_16",
    proId: "pro_9",
    consumerId: "user_morgan",
    consumerName: "Morgan Davis",
    journeyId: "journey_3",
    rating: 5,
    title: "The best realtor in Chicago, hands down",
    body: "Lisa helped us find our dream home in Evanston after just 3 weeks of searching. She knows the north side neighborhoods inside and out. Her negotiation skills saved us $15K on the purchase price. But what really sets Lisa apart is how she coordinates the entire team — lender, inspector, attorney, insurance — through Relays. The whole process felt seamless.",
    serviceCategory: "Realtor",
    verifiedClient: false,
    proResponse: {
      body: "Morgan, working with you and your family was such a joy! That Evanston Victorian is going to be an incredible home. Thank you for trusting me with such an important journey. 🏡✨",
      respondedAt: "2026-02-21T16:00:00Z",
    },
    helpful: 18,
    reported: false,
    createdAt: "2026-02-21T10:00:00Z",
  },
  {
    id: "review_17",
    proId: "pro_9",
    consumerId: "user_brendan",
    consumerName: "Brendan O.",
    rating: 5,
    body: "Lisa is the complete package — knowledgeable, responsive, great negotiator, and genuinely cares about her clients. She showed us 12 homes, was patient with our changing criteria, and ultimately helped us find something even better than what we originally wanted.",
    serviceCategory: "Realtor",
    verifiedClient: false,
    helpful: 10,
    reported: false,
    createdAt: "2026-01-30T14:00:00Z",
  },
  {
    id: "review_18",
    proId: "pro_9",
    consumerId: "user_priya_client",
    consumerName: "Nadia F.",
    rating: 4,
    body: "Lisa was wonderful throughout most of the process. Very knowledgeable about Lincoln Park and Lakeview. The only reason for 4 stars is that communication slowed a bit during the final week before closing, but everything worked out perfectly in the end.",
    serviceCategory: "Realtor",
    verifiedClient: false,
    helpful: 3,
    reported: false,
    createdAt: "2026-01-12T09:00:00Z",
  },

  // Mike Chen (pro_8) — Home Inspector — 1 review
  {
    id: "review_19",
    proId: "pro_8",
    consumerId: "user_north_shore",
    consumerName: "Patricia L.",
    rating: 2,
    title: "Good inspection but missed a plumbing issue",
    body: "Mike did a generally thorough job, but unfortunately missed a significant plumbing issue under the kitchen that we discovered 2 weeks after closing. It cost us $3,500 to fix. The rest of the inspection report was detailed and professional, but the miss was costly.",
    serviceCategory: "Home Inspector",
    verifiedClient: false,
    proResponse: {
      body: "Patricia, I'm very sorry about the plumbing issue. The area under your kitchen sink had limited access during the inspection which I noted in the report (p.14), but I understand the frustration. I'd like to discuss this further — please reach out to my office directly.",
      respondedAt: "2026-02-05T11:00:00Z",
    },
    helpful: 7,
    reported: false,
    createdAt: "2026-02-03T18:00:00Z",
  },

  // Frank Johnson (pro_10) — Realtor — 1 review
  {
    id: "review_20",
    proId: "pro_10",
    consumerId: "user_hyde_park",
    consumerName: "Andre J.",
    rating: 5,
    title: "Data-driven and dependable",
    body: "Frank's analytical approach to real estate is refreshing. He showed us market comps, neighborhood trends, and price history for every property we looked at. Helped us make an informed decision on a South Loop condo. Highly recommend for anyone who wants facts over fluff.",
    serviceCategory: "Realtor",
    verifiedClient: false,
    helpful: 5,
    reported: false,
    createdAt: "2026-02-18T12:00:00Z",
  },
];

/* ── Review Stats per Pro ─────────────────────────────────────── */

export const mockReviewStats: ReviewStats[] = [
  {
    proId: "pro_1",
    averageRating: 4.5,
    totalReviews: 312,
    ratingDistribution: { 1: 3, 2: 8, 3: 22, 4: 65, 5: 214 },
    responseRate: 78,
    avgResponseTime: "within 24 hours",
  },
  {
    proId: "pro_2",
    averageRating: 4.8,
    totalReviews: 198,
    ratingDistribution: { 1: 1, 2: 3, 3: 10, 4: 38, 5: 146 },
    responseRate: 65,
    avgResponseTime: "within 48 hours",
  },
  {
    proId: "pro_3",
    averageRating: 4.7,
    totalReviews: 156,
    ratingDistribution: { 1: 2, 2: 4, 3: 12, 4: 35, 5: 103 },
    responseRate: 55,
    avgResponseTime: "within 3 days",
  },
  {
    proId: "pro_4",
    averageRating: 4.9,
    totalReviews: 89,
    ratingDistribution: { 1: 0, 2: 1, 3: 3, 4: 12, 5: 73 },
    responseRate: 82,
    avgResponseTime: "within 24 hours",
  },
  {
    proId: "pro_8",
    averageRating: 4.8,
    totalReviews: 187,
    ratingDistribution: { 1: 1, 2: 5, 3: 8, 4: 30, 5: 143 },
    responseRate: 70,
    avgResponseTime: "within 48 hours",
  },
  {
    proId: "pro_9",
    averageRating: 4.9,
    totalReviews: 278,
    ratingDistribution: { 1: 1, 2: 3, 3: 9, 4: 42, 5: 223 },
    responseRate: 88,
    avgResponseTime: "within 12 hours",
  },
  {
    proId: "pro_10",
    averageRating: 4.8,
    totalReviews: 195,
    ratingDistribution: { 1: 2, 2: 4, 3: 11, 4: 34, 5: 144 },
    responseRate: 60,
    avgResponseTime: "within 48 hours",
  },
];

/* ── Mock Post-Service Follow-ups ─────────────────────────────── */

export const mockFollowUps: PostServiceFollowUp[] = [
  {
    id: "followup_1",
    type: "journey_complete",
    consumerId: "user_morgan",
    journeyId: "journey_3",
    title: "🎉 Journey Complete!",
    body: "Congratulations on closing your Evanston Victorian! You've officially made it through every step. How was your experience?",
    status: "completed",
    createdAt: "2026-02-20T10:15:00Z",
    completedAt: "2026-02-21T09:00:00Z",
  },
  {
    id: "followup_2",
    type: "review_prompt",
    consumerId: "user_morgan",
    journeyId: "journey_3",
    proId: "pro_9",
    proName: "Lisa Hartwell",
    title: "How was your experience with Lisa Hartwell?",
    body: "Your journey with Lisa is complete. Help other homebuyers by sharing your experience.",
    status: "completed",
    createdAt: "2026-02-20T10:20:00Z",
    completedAt: "2026-02-21T10:00:00Z",
  },
  {
    id: "followup_3",
    type: "review_prompt",
    consumerId: "user_morgan",
    journeyId: "journey_3",
    proId: "pro_1",
    proName: "Alex Martinez",
    title: "How was your experience with Alex Martinez?",
    body: "You worked with Alex during your home buying journey. Share how it went!",
    status: "completed",
    createdAt: "2026-02-20T10:25:00Z",
    completedAt: "2026-02-21T09:30:00Z",
  },
  {
    id: "followup_4",
    type: "review_prompt",
    consumerId: "user_jamie",
    journeyId: "journey_1",
    proId: "pro_9",
    proName: "Lisa Hartwell",
    title: "How was your experience with Lisa Hartwell?",
    body: "Lisa helped guide your Oak Park Bungalow purchase. Let others know what it was like working with her!",
    status: "pending",
    createdAt: "2026-02-16T10:00:00Z",
  },
  {
    id: "followup_5",
    type: "review_reminder",
    consumerId: "user_jamie",
    journeyId: "journey_1",
    proId: "pro_2",
    proName: "Jordan Lee",
    title: "Reminder: Share your experience with Jordan Lee",
    body: "You haven't reviewed Jordan yet. Your feedback helps other homebuyers make informed decisions.",
    status: "pending",
    createdAt: "2026-02-19T09:00:00Z",
  },
  {
    id: "followup_6",
    type: "nps_survey",
    consumerId: "user_morgan",
    journeyId: "journey_3",
    title: "How likely are you to recommend Relays?",
    body: "On a scale of 1-10, how likely are you to recommend Relays to a friend or colleague?",
    status: "completed",
    createdAt: "2026-02-20T10:30:00Z",
    completedAt: "2026-02-22T08:00:00Z",
    npsScore: 9,
  },
  {
    id: "followup_7",
    type: "nps_survey",
    consumerId: "user_jamie",
    journeyId: "journey_1",
    title: "How likely are you to recommend Relays?",
    body: "We'd love to hear — on a scale of 1-10, how likely are you to recommend Relays?",
    status: "pending",
    createdAt: "2026-02-16T10:05:00Z",
  },
];

/* ── Helpers ──────────────────────────────────────────────────── */

export function getReviewsForPro(proId: string): Review[] {
  return mockReviews.filter((r) => r.proId === proId);
}

export function getReviewStatsForPro(proId: string): ReviewStats | undefined {
  return mockReviewStats.find((s) => s.proId === proId);
}

export function getReviewsByConsumer(consumerId: string): Review[] {
  return mockReviews.filter((r) => r.consumerId === consumerId);
}

export function getReviewById(id: string): Review | undefined {
  return mockReviews.find((r) => r.id === id);
}

export function getFollowUpsForConsumer(consumerId: string): PostServiceFollowUp[] {
  return mockFollowUps.filter((f) => f.consumerId === consumerId);
}

export function getPendingFollowUps(consumerId: string): PostServiceFollowUp[] {
  return mockFollowUps.filter((f) => f.consumerId === consumerId && f.status === "pending");
}
