/* ── Relays — Mock Webhook / Events / Integration Data ─────────── */

import type {
  WebhookEndpoint,
  WebhookDelivery,
  APIKey,
  Integration,
  EventCatalogEntry,
  EventType,
} from "@/lib/types";

// ── Mock Webhook Endpoints ─────────────────────────────────────

export const mockWebhookEndpoints: WebhookEndpoint[] = [
  {
    id: "wh_01",
    url: "https://hooks.followupboss.com/v1/relays/ingest",
    secret: "whsec_a3b7c1d9e4f2g8h6j5k0l1m2n3o4p5q6",
    events: [
      "person.created",
      "person.updated",
      "journey.created",
      "journey.stage_changed",
      "booking.requested",
      "booking.accepted",
    ],
    status: "active",
    createdAt: "2026-01-15T09:30:00Z",
    lastDeliveryAt: "2026-02-16T14:22:33Z",
    failureCount: 0,
  },
  {
    id: "wh_02",
    url: "https://hooks.zapier.com/hooks/catch/12345/abcdef/",
    secret: "whsec_x9y8z7w6v5u4t3s2r1q0p9o8n7m6l5k4",
    events: [
      "journey.created",
      "journey.stage_changed",
      "referral.sent",
      "doc.uploaded",
    ],
    status: "paused",
    createdAt: "2026-01-28T16:45:00Z",
    lastDeliveryAt: "2026-02-10T08:15:00Z",
    failureCount: 0,
  },
  {
    id: "wh_03",
    url: "https://api.example-crm.io/webhooks/relays",
    secret: "whsec_j4k5l6m7n8o9p0q1r2s3t4u5v6w7x8y9",
    events: [
      "person.created",
      "booking.requested",
      "booking.accepted",
      "booking.declined",
      "connect.requested",
      "connect.accepted",
      "message.sent",
    ],
    status: "failed",
    createdAt: "2026-02-01T11:00:00Z",
    lastDeliveryAt: "2026-02-14T19:45:12Z",
    failureCount: 12,
  },
];

// ── Mock Webhook Deliveries ────────────────────────────────────

export const mockWebhookDeliveries: WebhookDelivery[] = [
  // Active endpoint — recent successes
  {
    id: "del_001",
    endpointId: "wh_01",
    eventId: "evt_20260216_a1b2c3",
    eventType: "journey.stage_changed",
    status: "delivered",
    statusCode: 200,
    responseMs: 142,
    attempts: 1,
    createdAt: "2026-02-16T14:22:33Z",
  },
  {
    id: "del_002",
    endpointId: "wh_01",
    eventId: "evt_20260216_d4e5f6",
    eventType: "booking.requested",
    status: "delivered",
    statusCode: 200,
    responseMs: 89,
    attempts: 1,
    createdAt: "2026-02-16T13:45:10Z",
  },
  {
    id: "del_003",
    endpointId: "wh_01",
    eventId: "evt_20260216_g7h8i9",
    eventType: "person.created",
    status: "delivered",
    statusCode: 200,
    responseMs: 201,
    attempts: 1,
    createdAt: "2026-02-16T12:30:45Z",
  },
  {
    id: "del_004",
    endpointId: "wh_01",
    eventId: "evt_20260215_j0k1l2",
    eventType: "journey.created",
    status: "delivered",
    statusCode: 200,
    responseMs: 167,
    attempts: 1,
    createdAt: "2026-02-15T16:20:00Z",
  },
  {
    id: "del_005",
    endpointId: "wh_01",
    eventId: "evt_20260215_m3n4o5",
    eventType: "booking.accepted",
    status: "delivered",
    statusCode: 200,
    responseMs: 95,
    attempts: 1,
    createdAt: "2026-02-15T11:10:22Z",
  },
  // Paused endpoint — older deliveries
  {
    id: "del_006",
    endpointId: "wh_02",
    eventId: "evt_20260210_p6q7r8",
    eventType: "journey.created",
    status: "delivered",
    statusCode: 200,
    responseMs: 312,
    attempts: 1,
    createdAt: "2026-02-10T08:15:00Z",
  },
  {
    id: "del_007",
    endpointId: "wh_02",
    eventId: "evt_20260209_s9t0u1",
    eventType: "referral.sent",
    status: "delivered",
    statusCode: 200,
    responseMs: 189,
    attempts: 1,
    createdAt: "2026-02-09T14:30:00Z",
  },
  {
    id: "del_008",
    endpointId: "wh_02",
    eventId: "evt_20260208_v2w3x4",
    eventType: "doc.uploaded",
    status: "delivered",
    statusCode: 200,
    responseMs: 267,
    attempts: 1,
    createdAt: "2026-02-08T10:00:00Z",
  },
  // Failed endpoint — failures and retries
  {
    id: "del_009",
    endpointId: "wh_03",
    eventId: "evt_20260214_y5z6a7",
    eventType: "booking.requested",
    status: "failed",
    statusCode: 500,
    responseMs: 4201,
    attempts: 5,
    createdAt: "2026-02-14T19:45:12Z",
  },
  {
    id: "del_010",
    endpointId: "wh_03",
    eventId: "evt_20260214_b8c9d0",
    eventType: "connect.requested",
    status: "retrying",
    statusCode: 500,
    responseMs: 3800,
    attempts: 3,
    nextRetryAt: "2026-02-16T20:00:00Z",
    createdAt: "2026-02-14T18:30:00Z",
  },
  {
    id: "del_011",
    endpointId: "wh_03",
    eventId: "evt_20260214_e1f2g3",
    eventType: "person.created",
    status: "failed",
    statusCode: 408,
    responseMs: 10000,
    attempts: 5,
    createdAt: "2026-02-14T17:15:00Z",
  },
  {
    id: "del_012",
    endpointId: "wh_03",
    eventId: "evt_20260213_h4i5j6",
    eventType: "message.sent",
    status: "failed",
    statusCode: 500,
    responseMs: 5100,
    attempts: 5,
    createdAt: "2026-02-13T22:00:00Z",
  },
  {
    id: "del_013",
    endpointId: "wh_03",
    eventId: "evt_20260213_k7l8m9",
    eventType: "booking.declined",
    status: "retrying",
    statusCode: 502,
    responseMs: 3200,
    attempts: 2,
    nextRetryAt: "2026-02-16T18:00:00Z",
    createdAt: "2026-02-13T15:30:00Z",
  },
  {
    id: "del_014",
    endpointId: "wh_01",
    eventId: "evt_20260214_n0o1p2",
    eventType: "person.updated",
    status: "delivered",
    statusCode: 200,
    responseMs: 134,
    attempts: 1,
    createdAt: "2026-02-14T09:00:00Z",
  },
  {
    id: "del_015",
    endpointId: "wh_01",
    eventId: "evt_20260213_q3r4s5",
    eventType: "journey.stage_changed",
    status: "delivered",
    statusCode: 200,
    responseMs: 178,
    attempts: 2,
    createdAt: "2026-02-13T11:45:00Z",
  },
  {
    id: "del_016",
    endpointId: "wh_03",
    eventId: "evt_20260212_t6u7v8",
    eventType: "connect.accepted",
    status: "failed",
    statusCode: 503,
    responseMs: 6200,
    attempts: 5,
    createdAt: "2026-02-12T14:20:00Z",
  },
  {
    id: "del_017",
    endpointId: "wh_02",
    eventId: "evt_20260207_w9x0y1",
    eventType: "journey.stage_changed",
    status: "delivered",
    statusCode: 200,
    responseMs: 145,
    attempts: 1,
    createdAt: "2026-02-07T09:30:00Z",
  },
];

// ── Mock API Keys ──────────────────────────────────────────────

export const mockAPIKeys: APIKey[] = [
  {
    id: "key_01",
    name: "Production",
    prefix: "rl_live_",
    lastFour: "8f3a",
    createdAt: "2026-01-10T12:00:00Z",
    lastUsedAt: "2026-02-16T14:30:00Z",
    status: "active",
  },
  {
    id: "key_02",
    name: "Development",
    prefix: "rl_test_",
    lastFour: "2d7c",
    createdAt: "2026-01-15T09:00:00Z",
    lastUsedAt: "2026-02-15T10:00:00Z",
    status: "active",
  },
  {
    id: "key_03",
    name: "Old Integration",
    prefix: "rl_live_",
    lastFour: "9x1b",
    createdAt: "2025-11-20T08:00:00Z",
    status: "revoked",
  },
];

// ── Mock Integrations ──────────────────────────────────────────

export const mockIntegrations: Integration[] = [
  {
    id: "int_fub",
    name: "Follow Up Boss",
    description: "Sync leads, contacts, and journey updates directly into Follow Up Boss.",
    logoUrl: "/integrations/followupboss.svg",
    category: "crm",
    connected: true,
    lastSyncAt: "2026-02-16T14:15:00Z",
    status: "connected",
  },
  {
    id: "int_kvcore",
    name: "kvCORE",
    description: "Bi-directional sync of contacts, lead sources, and transaction stages.",
    logoUrl: "/integrations/kvcore.svg",
    category: "crm",
    connected: false,
  },
  {
    id: "int_hubspot",
    name: "HubSpot",
    description: "Push journey events and contact updates into your HubSpot CRM pipeline.",
    logoUrl: "/integrations/hubspot.svg",
    category: "crm",
    connected: false,
  },
  {
    id: "int_salesforce",
    name: "Salesforce",
    description: "Enterprise-grade sync for contacts, opportunities, and custom objects.",
    logoUrl: "/integrations/salesforce.svg",
    category: "crm",
    connected: false,
  },
  {
    id: "int_gsheets",
    name: "Google Sheets",
    description: "Automatically log events, leads, and booking data to Google Sheets.",
    logoUrl: "/integrations/gsheets.svg",
    category: "spreadsheet",
    connected: true,
    lastSyncAt: "2026-02-16T12:00:00Z",
    status: "connected",
  },
  {
    id: "int_zapier",
    name: "Zapier",
    description: "Connect Relays to 6,000+ apps. Automate any workflow with triggers and actions.",
    logoUrl: "/integrations/zapier.svg",
    category: "automation",
    connected: true,
    lastSyncAt: "2026-02-16T13:30:00Z",
    status: "connected",
  },
  {
    id: "int_make",
    name: "Make (Integromat)",
    description: "Build complex automation scenarios with visual workflows and Relays triggers.",
    logoUrl: "/integrations/make.svg",
    category: "automation",
    connected: false,
  },
];

// ── Event Catalog ──────────────────────────────────────────────

export const eventCatalog: EventCatalogEntry[] = [
  // ── Person ──
  {
    type: "person.created",
    version: "v1",
    category: "Person",
    name: "Person Created",
    description: "Triggered when a new consumer or contact is added to Relays, either through sign-up, import, or referral.",
    triggerConditions: "New user registration, CSV import, or first referral creates a contact record.",
    samplePayload: {
      id: "evt_20260216_a1b2c3d4",
      type: "person.created",
      version: "v1",
      timestamp: "2026-02-16T14:30:00Z",
      idempotencyKey: "person.created_evt_20260216_a1b2c3d4",
      payload: {
        personId: "person_8f3a2d7c",
        email: "sarah.johnson@example.com",
        name: "Sarah Johnson",
        phone: "+13125550142",
        source: "referral",
        referredBy: "pro_1",
      },
    },
  },
  {
    type: "person.updated",
    version: "v1",
    category: "Person",
    name: "Person Updated",
    description: "Triggered when a consumer's profile information is modified, including name, email, phone, or preferences.",
    triggerConditions: "Any profile field update on a consumer record.",
    samplePayload: {
      id: "evt_20260216_e5f6g7h8",
      type: "person.updated",
      version: "v1",
      timestamp: "2026-02-16T15:00:00Z",
      idempotencyKey: "person.updated_evt_20260216_e5f6g7h8",
      payload: {
        personId: "person_8f3a2d7c",
        changes: {
          phone: { from: "+13125550142", to: "+13125550199" },
          name: { from: "Sarah Johnson", to: "Sarah M. Johnson" },
        },
      },
    },
  },
  // ── Journey ──
  {
    type: "journey.created",
    version: "v1",
    category: "Journey",
    name: "Journey Created",
    description: "Triggered when a new home-buying journey is created by a professional on behalf of a client.",
    triggerConditions: "Pro clicks 'New Journey' and saves the initial journey details.",
    samplePayload: {
      id: "evt_20260216_i9j0k1l2",
      type: "journey.created",
      version: "v1",
      timestamp: "2026-02-16T10:00:00Z",
      idempotencyKey: "journey.created_evt_20260216_i9j0k1l2",
      journeyId: "journey_4x8m2n",
      proId: "pro_1",
      payload: {
        journeyId: "journey_4x8m2n",
        title: "742 Evergreen Terrace",
        address: "742 Evergreen Terrace, Springfield, IL 62704",
        propertyType: "buying",
        stage: "pre_approval",
        client: {
          name: "Sarah Johnson",
          email: "sarah.johnson@example.com",
        },
        createdByProId: "pro_1",
      },
    },
  },
  {
    type: "journey.stage_changed",
    version: "v1",
    category: "Journey",
    name: "Journey Stage Changed",
    description: "Triggered when a journey advances (or regresses) to a different stage in the home-buying process.",
    triggerConditions: "Pro advances the journey stage via the Journey Flow UI.",
    samplePayload: {
      id: "evt_20260216_m3n4o5p6",
      type: "journey.stage_changed",
      version: "v1",
      timestamp: "2026-02-16T11:30:00Z",
      idempotencyKey: "journey.stage_changed_evt_20260216_m3n4o5p6",
      journeyId: "journey_4x8m2n",
      proId: "pro_1",
      payload: {
        journeyId: "journey_4x8m2n",
        previousStage: "offer_made",
        newStage: "offer_accepted",
        changedBy: "pro_1",
      },
    },
  },
  {
    type: "journey.owner_changed",
    version: "v1",
    category: "Journey",
    name: "Journey Owner Changed",
    description: "Triggered when a journey's owning professional is changed, e.g. handoff between agents.",
    triggerConditions: "Admin or broker reassigns a journey to a different pro.",
    samplePayload: {
      id: "evt_20260216_q7r8s9t0",
      type: "journey.owner_changed",
      version: "v1",
      timestamp: "2026-02-16T09:00:00Z",
      idempotencyKey: "journey.owner_changed_evt_20260216_q7r8s9t0",
      journeyId: "journey_4x8m2n",
      payload: {
        journeyId: "journey_4x8m2n",
        previousOwner: "pro_3",
        newOwner: "pro_1",
        reason: "Agent handoff — original agent on leave",
      },
    },
  },
  {
    type: "pro.added_to_journey",
    version: "v1",
    category: "Journey",
    name: "Pro Added to Journey",
    description: "Triggered when a professional is added to a journey's team roster to fill a service role.",
    triggerConditions: "Consumer or owning pro selects a professional from the curated group for a role.",
    samplePayload: {
      id: "evt_20260216_u1v2w3x4",
      type: "pro.added_to_journey",
      version: "v1",
      timestamp: "2026-02-16T12:15:00Z",
      idempotencyKey: "pro.added_to_journey_evt_20260216_u1v2w3x4",
      journeyId: "journey_4x8m2n",
      proId: "pro_2",
      payload: {
        journeyId: "journey_4x8m2n",
        proId: "pro_2",
        proName: "Jordan Lee",
        role: "Mortgage Lender",
        addedBy: "pro_1",
      },
    },
  },
  {
    type: "curated_group.changed",
    version: "v1",
    category: "Journey",
    name: "Curated Group Changed",
    description: "Triggered when a journey's associated curated group is updated or swapped.",
    triggerConditions: "Pro changes the curated group assignment for a journey.",
    samplePayload: {
      id: "evt_20260216_y5z6a7b8",
      type: "curated_group.changed",
      version: "v1",
      timestamp: "2026-02-16T13:00:00Z",
      idempotencyKey: "curated_group.changed_evt_20260216_y5z6a7b8",
      journeyId: "journey_4x8m2n",
      proId: "pro_1",
      payload: {
        journeyId: "journey_4x8m2n",
        previousGroupId: "grp_default",
        newGroupId: "grp_spanish_speakers",
        changedBy: "pro_1",
      },
    },
  },
  {
    type: "referral.sent",
    version: "v1",
    category: "Journey",
    name: "Referral Sent",
    description: "Triggered when a referral moment sends the curated top-3 recommendations to a consumer.",
    triggerConditions: "Referral moment is triggered (automatically or manually) and top-3 are sent.",
    samplePayload: {
      id: "evt_20260216_c9d0e1f2",
      type: "referral.sent",
      version: "v1",
      timestamp: "2026-02-16T14:00:00Z",
      idempotencyKey: "referral.sent_evt_20260216_c9d0e1f2",
      journeyId: "journey_4x8m2n",
      proId: "pro_1",
      consumerId: "person_8f3a2d7c",
      payload: {
        journeyId: "journey_4x8m2n",
        role: "Home Inspector",
        recommendedPros: ["pro_1", "pro_5", "pro_7"],
        sentTo: "sarah.johnson@example.com",
        channel: "email",
      },
    },
  },
  // ── Booking ──
  {
    type: "booking.requested",
    version: "v1",
    category: "Booking",
    name: "Booking Requested",
    description: "Triggered when a consumer requests a booking with a professional through Relays.",
    triggerConditions: "Consumer submits a booking request form on a pro's profile or via journey flow.",
    samplePayload: {
      id: "evt_20260216_g3h4i5j6",
      type: "booking.requested",
      version: "v1",
      timestamp: "2026-02-16T10:30:00Z",
      idempotencyKey: "booking.requested_evt_20260216_g3h4i5j6",
      journeyId: "journey_4x8m2n",
      proId: "pro_1",
      consumerId: "person_8f3a2d7c",
      payload: {
        bookingId: "bk_7x9m2p",
        proId: "pro_1",
        proName: "Alex Martinez",
        consumerId: "person_8f3a2d7c",
        consumerName: "Sarah Johnson",
        requestedDate: "2026-02-20",
        requestedTime: "10:00",
        serviceCategory: "Home Inspector",
        notes: "Older home, would like radon testing included",
      },
    },
  },
  {
    type: "booking.accepted",
    version: "v1",
    category: "Booking",
    name: "Booking Accepted",
    description: "Triggered when a professional accepts a pending booking request.",
    triggerConditions: "Pro clicks 'Accept' on a booking request in their dashboard.",
    samplePayload: {
      id: "evt_20260216_k7l8m9n0",
      type: "booking.accepted",
      version: "v1",
      timestamp: "2026-02-16T11:00:00Z",
      idempotencyKey: "booking.accepted_evt_20260216_k7l8m9n0",
      journeyId: "journey_4x8m2n",
      proId: "pro_1",
      consumerId: "person_8f3a2d7c",
      payload: {
        bookingId: "bk_7x9m2p",
        proId: "pro_1",
        confirmedDate: "2026-02-20",
        confirmedTime: "10:00",
        estimatedDuration: "2 hours",
      },
    },
  },
  {
    type: "booking.declined",
    version: "v1",
    category: "Booking",
    name: "Booking Declined",
    description: "Triggered when a professional declines a booking request.",
    triggerConditions: "Pro clicks 'Decline' on a booking request, optionally with a reason.",
    samplePayload: {
      id: "evt_20260216_o1p2q3r4",
      type: "booking.declined",
      version: "v1",
      timestamp: "2026-02-16T11:15:00Z",
      idempotencyKey: "booking.declined_evt_20260216_o1p2q3r4",
      journeyId: "journey_4x8m2n",
      proId: "pro_5",
      consumerId: "person_8f3a2d7c",
      payload: {
        bookingId: "bk_8y0n3q",
        proId: "pro_5",
        reason: "Scheduling conflict — fully booked that week",
        suggestedAlternative: "2026-02-27",
      },
    },
  },
  // ── Documents ──
  {
    type: "doc.requested",
    version: "v1",
    category: "Documents",
    name: "Document Requested",
    description: "Triggered when a professional or system requests a document from the consumer or another pro.",
    triggerConditions: "Pro clicks 'Request Document' in the journey document tracker, or system auto-requests based on stage.",
    samplePayload: {
      id: "evt_20260216_s5t6u7v8",
      type: "doc.requested",
      version: "v1",
      timestamp: "2026-02-16T09:30:00Z",
      idempotencyKey: "doc.requested_evt_20260216_s5t6u7v8",
      journeyId: "journey_4x8m2n",
      proId: "pro_2",
      payload: {
        documentId: "doc_3m7n9p",
        journeyId: "journey_4x8m2n",
        category: "pre_approval_letter",
        title: "Pre-Approval Letter",
        requestedBy: "pro_2",
        requestedFrom: "person_8f3a2d7c",
      },
    },
  },
  {
    type: "doc.uploaded",
    version: "v1",
    category: "Documents",
    name: "Document Uploaded",
    description: "Triggered when a document is uploaded to a journey's document tracker.",
    triggerConditions: "Any participant uploads a file to the journey documents section.",
    samplePayload: {
      id: "evt_20260216_w9x0y1z2",
      type: "doc.uploaded",
      version: "v1",
      timestamp: "2026-02-16T10:15:00Z",
      idempotencyKey: "doc.uploaded_evt_20260216_w9x0y1z2",
      journeyId: "journey_4x8m2n",
      consumerId: "person_8f3a2d7c",
      payload: {
        documentId: "doc_3m7n9p",
        journeyId: "journey_4x8m2n",
        category: "pre_approval_letter",
        title: "Pre-Approval Letter — Sunrise Mortgage",
        fileType: "application/pdf",
        fileSize: 245760,
        uploadedBy: "person_8f3a2d7c",
      },
    },
  },
  // ── Messaging ──
  {
    type: "connect.requested",
    version: "v1",
    category: "Messaging",
    name: "Connect Requested",
    description: "Triggered when a consumer sends a connection request to a professional (free-tier lead generation).",
    triggerConditions: "Consumer clicks 'Connect' on a pro's public profile or from the marketplace.",
    samplePayload: {
      id: "evt_20260216_a3b4c5d6",
      type: "connect.requested",
      version: "v1",
      timestamp: "2026-02-16T08:45:00Z",
      idempotencyKey: "connect.requested_evt_20260216_a3b4c5d6",
      proId: "pro_1",
      consumerId: "person_9g4b3e8f",
      payload: {
        connectRequestId: "cr_5k2m8n",
        proId: "pro_1",
        proName: "Alex Martinez",
        consumerId: "person_9g4b3e8f",
        consumerName: "Michael Chen",
        message: "I'm looking for a home inspector for a 1920s bungalow in Oak Park.",
        preferredContact: "in_app",
      },
    },
  },
  {
    type: "connect.accepted",
    version: "v1",
    category: "Messaging",
    name: "Connect Accepted",
    description: "Triggered when a professional accepts a consumer's connection request.",
    triggerConditions: "Pro clicks 'Accept' on an incoming connect request.",
    samplePayload: {
      id: "evt_20260216_e7f8g9h0",
      type: "connect.accepted",
      version: "v1",
      timestamp: "2026-02-16T09:15:00Z",
      idempotencyKey: "connect.accepted_evt_20260216_e7f8g9h0",
      proId: "pro_1",
      consumerId: "person_9g4b3e8f",
      payload: {
        connectRequestId: "cr_5k2m8n",
        proId: "pro_1",
        consumerId: "person_9g4b3e8f",
        conversationId: "conv_7p3q9r",
      },
    },
  },
  {
    type: "message.sent",
    version: "v1",
    category: "Messaging",
    name: "Message Sent",
    description: "Triggered when a message is sent within a Relays conversation thread.",
    triggerConditions: "Any participant sends a text, document share, or booking update message.",
    samplePayload: {
      id: "evt_20260216_i1j2k3l4",
      type: "message.sent",
      version: "v1",
      timestamp: "2026-02-16T13:45:00Z",
      idempotencyKey: "message.sent_evt_20260216_i1j2k3l4",
      journeyId: "journey_4x8m2n",
      proId: "pro_1",
      consumerId: "person_8f3a2d7c",
      payload: {
        messageId: "msg_2n8p4q",
        conversationId: "conv_6o2p8q",
        senderId: "pro_1",
        senderRole: "pro",
        content: "Hi Sarah, just confirming our inspection is set for Thursday at 10am. I'll bring radon testing equipment as requested.",
        type: "text",
      },
    },
  },
  // ── Verification ──
  {
    type: "verification.completed",
    version: "v1",
    category: "Verification",
    name: "Verification Completed",
    description: "Triggered when a professional's license verification process completes (approved or rejected).",
    triggerConditions: "OCR auto-verification completes, or admin manually reviews and approves/rejects a verification request.",
    samplePayload: {
      id: "evt_20260216_m5n6o7p8",
      type: "verification.completed",
      version: "v1",
      timestamp: "2026-02-16T16:00:00Z",
      idempotencyKey: "verification.completed_evt_20260216_m5n6o7p8",
      proId: "pro_1",
      payload: {
        verificationId: "ver_4r7s1t",
        proId: "pro_1",
        proName: "Alex Martinez",
        type: "license_upload",
        status: "approved",
        confidence: 0.97,
        licenseNumber: "HI-2019-045832",
        expiresAt: "2027-06-30",
      },
    },
  },
];

// ── Helper: get deliveries for an endpoint ─────────────────────

export function getDeliveriesForEndpoint(endpointId: string): WebhookDelivery[] {
  return mockWebhookDeliveries.filter((d) => d.endpointId === endpointId);
}

// ── Helper: get event catalog entry by type ────────────────────

export function getEventCatalogEntry(type: EventType): EventCatalogEntry | undefined {
  return eventCatalog.find((e) => e.type === type);
}

// ── Helper: get events by category ─────────────────────────────

export function getEventsByCategory(category: string): EventCatalogEntry[] {
  return eventCatalog.filter((e) => e.category === category);
}
